import { AuthProvider, DataProvider, ThemeProvider } from "@/app/providers";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NerdIF 2024",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning={true} >
      <AuthProvider>
        <DataProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <body className={inter.className}>
              <Toaster richColors />
              <Navbar />
              {children}
            </body>
          </ThemeProvider>
        </DataProvider>
      </AuthProvider>
    </html>
  );
}
